server:
  port: 9090
spring:
  application:
    name: "roc-cache-center"
roc:
  mvc:
    enabled: true
    enable-default-errors-handler: true
    enable-default-valid-rule: true
    global-time-format-regex: "yyyy-MM-dd HH:mm:ss"
  cache:
    enabled: true
    broadcast: "none"
    l1-cache-name: "caffeine"
    l1-cache-properties:
      region:
        default: "1000, 30m"
        roc: "2000, 30m"
    l2-cache-name: "none"
    l2-cache-properties:
      storage: "generic"
      scheme: "redis-cluster"
      # k8s下需要部署在内网
      hosts: "xxx.xxx.xxx.xxx:32002"
      password: ""
      database: "0"
      maxTotal: "100"
      maxIdle: "10"
      minIdle: "10"
      timeout: "10000"
    serialization: "fastjson"
    sync-ttl-to-redis: true
    default-cache-null-object: true